
image_size = [256, 256]

[data_module_config]
stage = 'TWO'
data_root = 'data'
test_batch_size = 16
preload = false
debug = false

[tester_config]
model = 'hrnet18'  # 48, 32, 18
pretrain_load_dir = 'output/train_s2_18_256'
pretrain_load_prefix = '300'