
image_size = [256, 256]
test_result_path = 'output/test_s1_32_256/test_result.csv'
pretrain_load_dir = 'output/train_s1_32_256'
pretrain_load_prefix = '400'
model = 'hrnet32'

[dataset_config]
stage = 'ONE'
data_root = 'data'
preload = false

